[application]

# App (Project) Name
name = "memo_dioxus"

[web.app]

# HTML title tag content
title = "memo_dioxus"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

 [bundle]
publisher = "my example publisher"
identifier = "com.example.app"